# These are supported funding model platforms

Patreon Supporters: 

    Aedan Mac - $5
    
Investors:
    
    Wise Doctor - TBD
    
Affiliates:

    VR Cover - https://vrcover.com/#UGLOFFICIAL
    ULTI - https://ultisupps.rfrl.co/5d9r1
